addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"              % "0.14.7")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"            % "1.11.2")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"               % "0.7.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.6.1")
