name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache
      uses: coursier/cache-action@v6
    - name: Setup Scala
      uses: olafurpg/setup-scala@v11
      with:
        java-version: "openjdk@1.17"
    - name: Build and Test
      run: sbt -v +test
