name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Java and Scala
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'sbt'
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
    - name: Build and Test
      run: sbt -v test
